### ISSUE TITLE
Kernel Panic on cache mapped to an unformatted volume

### ISSUE THREAD

**Issue by bberberov** [pkoutoupis/rapiddisk#15] opened 2016-11-18 02:36 UTC
I was able to trigger a kernel panic reliably with the following steps:

0. I have a disk with a GPT label and a BIOS Boot partition.
1. Create a volume with `gdisk` but do not format it.  For example `sda11`.
2. `rapiddisk --attach 256`
3. `rapiddisk --cache-map rd0 /dev/sda11`
4. **Kernel Panic**

I'm running and updated OpenSUSE Tumbleweed.

```
# uname -sr
Linux 4.8.7-1-default
```

```
# dkms status 
rapiddisk, 4.4, 4.8.4-1-default, x86_64: installed
rapiddisk, 4.4, 4.8.6-2-default, x86_64: installed
rapiddisk, 4.4, 4.8.7-1-default, x86_64: installed
```

I'll see if the panic is somewhere in the logs.  Otherwise I'll have to post an image from the console.

**Comment by pkoutoupis** [comment] 2016-11-18 17:06
That doesn't seem to make any sense, because the mapping is all at the block level, irrespective of the drive format. I will try to reproduce locally but I am more curious as to if this may be 4.8+ specific (since there were changes made for that kernel in the last release).

**Comment by pkoutoupis** [comment] 2016-11-19 20:13
Can you pull from the latest and retest....

```
commit 05b77512ce6244f8863ef439b7ca549bb1bbc285
Author: Petros Koutoupis <petros@petroskoutoupis.com>
Date:   Sat Nov 19 14:12:09 2016 -0600

    Pushing 4.5.

```

**Comment by bberberov** [comment] 2016-11-20 21:37
Do you have a beta repo?  It would be easier for me to verify.  I am not confident the build environment on this system is set up correctly.

**Comment by pkoutoupis** [comment] 2016-11-20 21:54
I still have my tumbleweed VM (x86_64), if you give me some time, I can run a zypper update and then create an RPM. Would this be easier?

**Comment by pkoutoupis** [comment] 2016-11-22 02:55
OK. Make sure that DKMS is installed....
http://downloads.rapiddisk.org/pub/beta/rapiddisk-4.5-1.osuse_tumbleweed.x86_64.rpm

**Comment by bberberov** [comment] 2016-11-22 20:46
Just tested it.  I still get a kernel panic.

**Comment by pkoutoupis** [comment] 2016-11-22 20:55
Hmmm. Just to humor me, can you provide the output of modinfo rapiddisk and modinfo rapiddisk-cache?

This doesn't make any sense. It works without issue in my Tumbleweed setup.

**Comment by bberberov** [comment] 2016-11-22 22:11
At first, `modprobe` was not working.  The module was just built and not installed.

```console
# modinfo rapiddisk
filename:       /lib/modules/4.8.7-1-default/kernel/rapiddisk/rapiddisk.ko
Copyright:      Copyright 2010 - 2015 Petros Koutoupis
version:        4.5
description:    RapidDisk is an enhanced RAM disk block device driver.
author:         Petros Koutoupis <petros@petroskoutoupis.com>
license:        GPL
srcversion:     ADE038BA8C90C81CCE29C7D
depends:        
vermagic:       4.8.7-1-default SMP preempt mod_unload modversions 
parm:           max_sectors: Maximum sectors (in KB) for the request queue. (Default = 127) (int)
parm:           nr_requests: Number of requests at a given time for the request queue. (Default = 128) (int)
parm:           rd_nr: Maximum number of RapidDisk devices to load on insertion. (Default = 0) (int)
parm:           rd_size: Size of each RAM disk (in KB) loaded on insertion. (Default = 0) (int)
parm:           rd_max_nr: Maximum number of RAM Disks. (Default = 128) (int)
# modinfo rapiddisk-cache 
filename:       /lib/modules/4.8.7-1-default/kernel/rapiddisk/rapiddisk-cache.ko
Copyright:      Copyright 2010 - 2016 Petros Koutoupis
version:        4.5
description:    RapidDisk-Cache DM target is a write-through caching target with RapidDisk volumes.
author:         Petros Koutoupis <petros@petroskoutoupis.com>
license:        GPL
srcversion:     2868566C14249D879AF84A8
depends:        dm-mod
vermagic:       4.8.7-1-default SMP preempt mod_unload modversions
```

It looks like two different kernel panics:
_____
![20161122_151137](https://cloud.githubusercontent.com/assets/7432115/20544021/afc6f74e-b0cd-11e6-889d-a8910afa6687.jpg)
_____
![20161122_151632_10](https://cloud.githubusercontent.com/assets/7432115/20544027/bb287cb6-b0cd-11e6-8739-d5286cc0b73e.jpg)

![20161122_151636_3](https://cloud.githubusercontent.com/assets/7432115/20544032/bfe553be-b0cd-11e6-8982-0f187d7da651.jpg)

**Comment by pkoutoupis** [comment] 2016-11-22 23:35
**OS**
```
petros@nohostname:/etc> cat os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20161118"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20161118"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20161118"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Kernel**
```
petros@nohostname:/> uname -a
Linux nohostname 4.8.8-1-default #1 SMP PREEMPT Tue Nov 15 07:53:56 UTC 2016 (7b7d4ed) x86_64 x86_64 x86_64 GNU/Linux
```

**SCSI device**
```
petros@nohostname:/etc> cat /proc/partitions |grep sdb
   8       16    1048576 sdb
   8       17          1 sdb1
   8       18     102400 sdb2
   8       19     102400 sdb3
   8       20     740352 sdb4
   8       21      51200 sdb5
   8       22      20480 sdb6
   8       23      27648 sdb7
```

**Cache Mappings**
```
List of RapidDisk-Cache mapping(s):

 RapidDisk-Cache Target 1: rc-wt_sdb5	Cache: rd3  Target: sdb5 (WRITE THROUGH)
 RapidDisk-Cache Target 2: rc-wt_sdb6	Cache: rd2  Target: sdb6 (WRITE THROUGH)
 RapidDisk-Cache Target 3: rc-wt_sdb7	Cache: rd1  Target: sdb7 (WRITE THROUGH)
 RapidDisk-Cache Target 4: rc-wt_sdb4	Cache: rd0  Target: sdb4 (WRITE THROUGH)
```

**Formatted with Ext4 and mounted:**
```
petros@nohostname:/etc> df |grep sdb
/dev/mapper/rc-wt_sdb4    712320    1464    659036   1% /mnt/mnt1
/dev/mapper/rc-wt_sdb5     45478    1038     40856   3% /mnt/mnt2
/dev/mapper/rc-wt_sdb6     18803     332     17038   2% /mnt/mnt3
/dev/mapper/rc-wt_sdb7     25745     659     23152   3% /mnt/mnt4
```

Again, I am not sure why you are experiencing such issues.....

Can you do me a favor and provide the following for your sda drive (substitute below):

```
petros@nohostname:~> cat /sys/block/sdb/queue/logical_block_size 
512
```

**Comment by pkoutoupis** [comment] 2016-11-23 01:22
I even did the same thing after setting the volume to GPT:

```
petros@nohostname:~> sudo fdisk -l /dev/sdb
Disk /dev/sdb: 1 GiB, 1073741824 bytes, 2097152 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: D149C02B-6C17-478D-BDE5-C95C76A3E61C

Device       Start     End Sectors  Size Type
/dev/sdb1     2048  104447  102400   50M Linux filesystem
/dev/sdb2   104448  206847  102400   50M Linux filesystem
/dev/sdb3   206848  309247  102400   50M Linux filesystem
/dev/sdb4   309248  411647  102400   50M Linux filesystem
/dev/sdb5   411648  514047  102400   50M Linux filesystem
/dev/sdb6   514048  616447  102400   50M Linux filesystem
/dev/sdb7   616448  718847  102400   50M Linux filesystem
/dev/sdb8   718848  821247  102400   50M Linux filesystem
/dev/sdb9   821248  923647  102400   50M Linux filesystem
/dev/sdb10  923648 1026047  102400   50M Linux filesystem
/dev/sdb11 1026048 2097118 1071071  523M Linux filesystem
```

**Cache Mapping**

```
List of RapidDisk-Cache mapping(s):

 RapidDisk-Cache Target 1: rc-wt_sdb11	Cache: rd0  Target: sdb11 (WRITE THROUGH)
```

**Formatted and mounted:**

```
petros@nohostname:~> df|grep sdb
/dev/mapper/rc-wt_sdb11    510704     804    472416   1% /mnt
```

**Comment by bberberov** [comment] 2016-11-23 05:07
I think you have fixed it.

```console
$ sudo rapiddisk --list
rapiddisk 4.5
Copyright 2011-2016 Petros Koutoupis

List of RapidDisk device(s):

 RapidDisk Device 1: rd11       Size (KB): 131072
 RapidDisk Device 2: rd3        Size (KB): 131072
 RapidDisk Device 3: rd1        Size (KB): 131072
 RapidDisk Device 4: rd8        Size (KB): 131072
 RapidDisk Device 5: rd14       Size (KB): 131072
 RapidDisk Device 6: rd6        Size (KB): 131072
 RapidDisk Device 7: rd12       Size (KB): 131072
 RapidDisk Device 8: rd4        Size (KB): 131072
 RapidDisk Device 9: rd10       Size (KB): 131072
 RapidDisk Device 10: rd2       Size (KB): 131072
 RapidDisk Device 11: rd0       Size (KB): 131072
 RapidDisk Device 12: rd9       Size (KB): 131072
 RapidDisk Device 13: rd15      Size (KB): 131072
 RapidDisk Device 14: rd7       Size (KB): 131072
 RapidDisk Device 15: rd13      Size (KB): 131072
 RapidDisk Device 16: rd5       Size (KB): 131072

List of RapidDisk-Cache mapping(s):

 RapidDisk-Cache Target 1: rc-wt_sda11  Cache: rd0  Target: sda11 (WRITE THROUGH)
 RapidDisk-Cache Target 2: rc-wt_home   Cache: rd2  Target: sda3  (WRITE THROUGH)

```

However, it took me more than ~70 tries to get the modules properly installed.  I think they build fine.
```console
$ find /var/lib/dkms -name 'rapiddisk*'        
/var/lib/dkms/rapiddisk
/var/lib/dkms/rapiddisk/4.5/build/rapiddisk.c
/var/lib/dkms/rapiddisk/4.5/build/rapiddisk-cache.c
/var/lib/dkms/rapiddisk/4.5/4.8.8-1-default/x86_64/module/rapiddisk-cache.ko
/var/lib/dkms/rapiddisk/4.5/4.8.8-1-default/x86_64/module/rapiddisk.ko
```
But `dkms` does not install them correctly.  This is the unsuccessful result:
```console
$ find /lib/modules -name 'rapiddisk*' -ls | cut -c 74-
/lib/modules/4.8.8-1-default/kernel/rapiddisk
/lib/modules/4.8.7-1-default/weak-updates/lib/modules/4.8.8-1-default/kernel/rapiddisk
/lib/modules/4.8.7-1-default/weak-updates/lib/modules/4.8.8-1-default/kernel/rapiddisk/rapiddisk-cache.ko -> /lib/modules/4.8.8-1-default/kernel/rapiddisk//rapiddisk-cache.ko
/lib/modules/4.8.7-1-default/weak-updates/lib/modules/4.8.8-1-default/kernel/rapiddisk/rapiddisk.ko -> /lib/modules/4.8.8-1-default/kernel/rapiddisk//rapiddisk.ko
/lib/modules/4.8.7-1-default/kernel/rapiddisk
```
Successful result:
```console
$ find /lib/modules -name 'rapiddisk*' -ls | cut -c 74-
/lib/modules/4.8.8-1-default/kernel/rapiddisk
/lib/modules/4.8.8-1-default/kernel/rapiddisk/rapiddisk-cache.ko
/lib/modules/4.8.8-1-default/kernel/rapiddisk/rapiddisk.ko
/lib/modules/4.8.7-1-default/weak-updates/lib/modules/4.8.8-1-default/kernel/rapiddisk
/lib/modules/4.8.7-1-default/weak-updates/lib/modules/4.8.8-1-default/kernel/rapiddisk/rapiddisk-cache.ko -> /lib/modules/4.8.8-1-default/kernel/rapiddisk//rapiddisk-cache.ko
/lib/modules/4.8.7-1-default/weak-updates/lib/modules/4.8.8-1-default/kernel/rapiddisk/rapiddisk.ko -> /lib/modules/4.8.8-1-default/kernel/rapiddisk//rapiddisk.ko
/lib/modules/4.8.7-1-default/kernel/rapiddisk
```

`dkms` tells me that `dracut` exits with error 1 and I believe it does some kind of rollback.  I don't want to try it again to get the console output since it might remove the modules again and I don't want to deal with getting them back.  When the next kernel update removes/corrupts them, I'll get the output.

Also, I get 16 128MiB RapidDisks by default now as you can see.

**Comment by pkoutoupis** [comment] 2016-11-23 11:28
That multiple rapiddisk volumes stuff is my fault. I forgot to tweak one file before doing the rpmbuild. I can always rebuild the rpm with the tweak.

**Comment by pkoutoupis** [comment] 2016-11-23 11:30
That multiple rapiddisk volumes stuff is my fault. I forgot to tweak one file before doing the rpmbuild. I can always rebuild the rpm with the tweak.

As for the dkms stuff, I guess it is more motivation to look into the other module build system. :-D

**Comment by pkoutoupis** [comment] 2016-11-23 13:45
I will close this issue on the basis that you validated that it now works. Any DKMS related stuff can continue with the #14 enhancement work.

**Closed by pkoutoupis** 2016-11-23 13:45 UTC
Labels: bug
