### ISSUE TITLE
writeback mode?

### ISSUE THREAD

**Issue by syadnom** [pkoutoupis/rapiddisk#23] opened 2017-12-18 17:17 UTC
I have a use-case where writeback mode is ideal.  To clarify so we both know what I mean, I want to consider the write complete when it's written to the rdX device then write that to disk async.  

I'd also like to see a timed flush and delay write.

here is the scenario

many small writes come in, enough to overwhelm a spindled disks random writes
some reads come in and that hurts random writes even more.
data is at a high enough volume that it does need written pretty soon or the cache will overflow.

want:
write to rdX, rd waits to write that to disk for a timer, then flushes to disk creating a write-deferred cache.  This turns overwhelming random writes into a comfortable amount of sequential writes.

This might look like a corner case, but it's a very common scenario in security camera storage systems.  Might only have ~12MBps in writes, but those are random and overcome a WD Red quickly.  A Write-Deferred option solves this 100%.

There is evidence of this too.  The Windows program PrimoCache does exactly this and it allows a windows server to handle 4x as many streams easily.

**Comment by syadnom** [comment] 2017-12-20 22:13
"Traditional RAM is volatile and by enabling a write-back caching mode
without some form of not losing cached data in RAM would result in user
data loss or possibly corruption"
Absolutely true, but there are valid and common use cases where a small
amount of data loss isn't a big deal.  ANY kind of data logging this
basically applies to because the power loss that would loose 30 seconds of
data also takes down the sensors.  Very little concern over the difference
between losing 5 minutes or 5 minutes and 30 seconds of data.  Security
cameras are the same deal.

ext4 is a bad filesystem for small files and many directories, the kind of
thing that security systems and data loggers write. XFS is by far the
preferred filesystem for these workloads.


*all* circumstances that use RAM caching can and will result in data loss.
 the question is that tolerable or not.  In the circumstances I describe
above, they are acceptable.


This is unrelated, but I'm doing this now via a convoluted process with
aufs and ramdisks.  Create a ramdisk and a directory on a hard disk.  Mount
aufs over the top with writes going to the ramdisk.  rsync
--remove-source-files from ramdisk to directory in the background on a
timer.  This is at the file level but does result in sequential writes.
The downside is aufs doesn't do a fantastic job of tracking large numbers
of files in the overlay so the VMS software can get a bit confuse with
files vanishing and re-appearing as the indexes get sorted.

I've tweaked this to the maximum.  First doing a plain rsync with a file
list, waiting a few minutes, then doing the 'move' against that file list
so I can let aufs get it's indexes up to date and it 'works'.

This has all the downsides of RAM cache which are unavoidable, but it is
very effectively a delayed write cache for the hard drive.  It's got an
additional downside that as the file structure on the drive grows, rsync
uses more and more cpu resources to build the file list.

I think rapiddisk is the closest project to accomplishing a true
delayed-write cache because it's already able to do regular caching that is
seamless.

**Comment by pkoutoupis** [comment] 2017-12-22 18:06
> XFS is by far the preferred filesystem for these workloads.

In my experience, XFS also suffers with small file data, more specifically on reads. But I imagine that this is not the typical I/O profile hitting these disks anyway. They are probably very write heavy and read less frequently (on an-as-needed basis).

> I think rapiddisk is the closest project to accomplishing 
> a true delayed-write cache because it's already able to do
> regular caching that is seamless.

Well, it doesn't yet but let me give this some thought and see how much work it would take (i.e. to batch writes at set intervals).

**Comment by syadnom** [comment] 2017-12-22 20:04
These aren’t terribly small files, just many. Write heavy, many directories
build up over time.  I would estimate XFS 2. better for this particular
work load.

**Comment by Shub77** [comment] 2020-05-19 19:10
Hi there,

I believe a write-back mode would be useful. It will be user's choice to undertake a risk in exchange of (much) higher speeds.

My 2 cents!

**Comment by krismoon** [comment] 2021-05-24 04:41
I also have a use case where writeback would be very advantageous - essentially I don't care if the data is lost as long as when it is not lost (i.e. the most likely scenario is no server crash/reboot) it is able to cache the write quickly and allow the process to move on while it copies that data back to the disk.  In a nutshell I don't care if there is data loss because even if there was no data loss , the process being interrupted would mean I need to start again anyway so data loss or no it makes no difference - however the write performance gain would make a huge difference in the 'normal case'.

**Comment by pkoutoupis** [comment] 2021-05-28 17:10
Instead of writing a writecache implementation into RapidDisk-Cache, I am considering on writing a wrapper into the CLI for dm-writecache and integrate that into the current stack. Note - I will not touch the dm-writecache code. I will only focus on adding the necessary pieces into userspace to have it play nice with the existing code.

**Comment by pkoutoupis** [comment] 2021-06-06 18:46
@krismoon (and others), I pushed code to [https://github.com/pkoutoupis/rapiddisk/tree/feature/writecache_cli_wrapper](https://github.com/pkoutoupis/rapiddisk/tree/feature/writecache_cli_wrapper). I still need to do some testing before merging it but it adds dm-writecache functionality to the userspace admin utility. This is what the command looks like:

```
$ sudo ./rapiddisk -m rd0 -b /dev/sdd -p wb
```

Similar to any other cache mapping command BUT you specify wb for writeback instead of the other options.

```
$ sudo ./rapiddisk -l
rapiddisk 7.2.0
Copyright 2011 - 2021 Petros Koutoupis

List of RapidDisk device(s):

 RapidDisk Device 1: rd1	Size (KB): 65536
 RapidDisk Device 2: rd2	Size (KB): 131072
 RapidDisk Device 3: rd0	Size (KB): 65536

List of RapidDisk-Cache mapping(s):

 RapidDisk-Cache Target 1: rc-wa_sdf	Cache: rd2  Target: sdf (WRITE AROUND)
 RapidDisk-Cache Target 2: rc-wt_sdc	Cache: rd1  Target: sdc (WRITE THROUGH)
 dm-writecache Target   3: rc-wb_sdd	Cache: rd0  Target: sdd (WRITEBACK)
```

**Comment by krismoon** [comment] 2021-06-08 12:41
This is great thanks Petros 🙂

Was able to get a test running, two things I had trouble with, dkms didn't
work and once I got writes going I started to see cpu soft lock errors (not
100% it was because of the writecache)

Thanks,
Kris

**Comment by pkoutoupis** [comment] 2021-06-08 14:26
@krismoon Good catch. Does this change address the DKMS issue?
```
diff --git a/module/Makefile b/module/Makefile
index b5a818b..71e2b52 100644
--- a/module/Makefile
+++ b/module/Makefile
@@ -15,7 +15,7 @@
 #
 # SPDX-License-Identifier: GPL-2.0-only
 
-VERSION = 7.1.0
+VERSION = 7.2.0
 
 ifeq ($(KSRC),)
        KSRC := /lib/modules/$(shell uname -r)/build
```

Also, as for the soft lock errors, even though I won't be changing dm-writecache code, I wonder if we can tune the dmsetup parameters. Can you please provide more details on the stack trace and the I/O profile hitting the cache mapping?

**Comment by pkoutoupis** [comment] 2021-06-09 23:35
@krismoon: it does not appear to be related to dm-writecache. If you cannot reproduce then I will not worry for now. Thank you for taking it for a test run. I will do more testing here and hopefully merge it soon (to master).

**Comment by krismoon** [comment] 2021-06-10 16:50
Glad to be of some small help - this additon to rapiddisk was a significant
help to me :)

Still working on error reproduction, my server had a hardware issue that
looks fixed now so trying again - in the meantime I did find this in the
kernel log when loading rapiddisk, not sure if its me that did set up wrong
or might indicate an issue.

Jun 10 12:40:18 x-ProLiant-DL380p-Gen8 kernel: [19467.244244] rapiddisk:
loading out-of-tree module taints kernel.
Jun 10 12:40:18 x-ProLiant-DL380p-Gen8 kernel: [19467.244304] rapiddisk:
module verification failed: signature and/or required key missing -
tainting kernel
Jun 10 12:40:29 x-ProLiant-DL380p-Gen8 kernel: [19478.432688] rapiddisk:
Attached rd0 of 17179869184 bytes in size.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by pkoutoupis** [comment] 2021-06-11 12:39
You did not do anything wrong. Modern distributions build their kernels to sign all in-tree modules that were built during compilation. Seeing how this is an out-of-tree module and not signed by the same or similar process, the kernel will issue the above warning. Nothing changes in terms of kernel (or module) functionality as a result. This is nothing to be concerned about.

**Comment by Augusto7743** [comment] 2021-06-12 11:13
Instead of writing a writecache implementation into RapidDisk-Cache, I am considering on 
"writing a wrapper into the CLI for dm-writecache and integrate that into the current stack"
You are saying dm-writeback will use rapiddisk ramdisk ?
Unhappily not is simple when starting the system attach an rapiddisk cache to mounted partition root and home.
Is simple to unmounted partitions.
I am a new Linux user.
I understand that is possible enable rapiddisk cache to partition root , but in moment not figured where I can see any information to do it.
When that wrapper be integrated in rapiddisk module will has any command line to automatically add rapiddisk cache in system startup to system partitions ?

That will help ... few hours accessing internet and stacer display write total 1 GB even using an browse disabled temporary files.
I understand your side about avoiding problems with users losing data if using writeback , but others users use eletric protection ( no breaks ) thus avoid problems.

In any way ... is an good work.
I had used windows for years and my little time experience using Linux is how if the softwares are much more well done looking how if the programmer is the real code owner ... really an company using code from an worker that was fired is ... I not understand if github allow post simple message about it.

Here trying use rapiddisk , but unhappily to moment I not figure how attach cache to partition root when the system is starting. In a moment will work.
God bless you.
Have an nice day.

**Comment by pkoutoupis** [comment] 2021-06-12 14:56
I merged this into master and cut release 7.2.0: https://github.com/pkoutoupis/rapiddisk/releases/tag/7.2.0.

**Closed by pkoutoupis** 2021-06-12 14:56 UTC
Labels: enhancement

**Comment by mircot80** [comment] 2021-06-13 20:13
Hello.  I did not understand if there is a possibility to enable write-back, thanks.

**Comment by pkoutoupis** [comment] 2021-06-13 21:42
@mircot80: Yes. Merged into release 7.2.0 is the ability to enabled write-back using a volatile RAM-based cache volume. Remember, this is dangerous and should only be used with caution. It relies on dm-writecache which is provided by the mainline Linux kernel and modern Linux distros. To map a RapidDisk RAM drive as a writeback cache to a slower backend drive:

```
$ sudo rapiddisk -m rd0 -b /dev/sdd -p wb
```

It is the "wb" for the caching policy that defines it.

**Comment by mircot80** [comment] 2021-06-16 06:55
ok thanks, it works.
I'm testing it with chia plotter (madmax) but with the cache enabled the performance is lower.

Grazie saluti
Mirco Tonin
Assistenza Informatica
email: ***@***.******@***.***>
cell: 333 2698514

Da: Petros Koutoupis ***@***.***>
Inviato: domenica 13 giugno 2021 23:43
A: pkoutoupis/rapiddisk ***@***.***>
Cc: Assistenza Informatica - Tonin Mirco ***@***.***>; Mention ***@***.***>
Oggetto: Re: [pkoutoupis/rapiddisk] writeback mode? (#23)


@mircot80<https://github.com/mircot80>: Yes. Merged into release 7.2.0 is the ability to enabled write-back using a volatile RAM-based cache volume. Remember, this is dangerous and should only be used with caution. It relies on dm-writecache which is provided by the mainline Linux kernel and modern Linux distros. To map a RapidDisk RAM drive as a writeback cache to a slower backend drive:

$ sudo rapiddisk -m rd0 -b /dev/sdd -p wb

It is the "wb" for the caching policy that defines it.

**Comment by pkoutoupis** [comment] 2021-06-16 14:14
Lower performance when compared to what? The backing store? How large is your RAM drive? What is the I/O being sent to the mapping? Also remember, the focal point of write back caching is to accelerate random access writes and not sequential.

**Comment by krismoon** [comment] 2021-06-16 21:21
Not sure I follow, why would sequential writes or large sequential writes not benefit from a writeback cache... Assuming the backing store is slow (i.e. mechanical HDD) and the data being written is less than the cache size, why would performance degrade?

**Comment by pkoutoupis** [comment] 2021-06-16 21:32
It isn't that they don't benefit at all. Sure, they do. But typically the backing store, even if it is spinning rust performs decently well when doing large file sequential writes. Or sequential write access in general. Random small files is where it really hurts and having a write back cache helps alleviate that pain. One drive can go from a 100 MB/s sequential write (no cache) to a 4 MB/s random write.

**Comment by syadnom** [comment] 2021-06-17 02:21
Large sequential writes don’t use any cache at all.  You’re going from
cpu>ram .  Add the cache and it does nothing except add a write to that
cache across the pcie bus which is much slower.

You’ll have literally zero cache hits mining chia on cached storage so best
case it gives you nothing, but adding a cache means more data on whatever
bus your storage is on.

I’m sitting on over 60,000 plots right now.  I have a full rack of 16 core
32 thread machines with 288GB of ram in each.   I’m telling you as a ‘pro’
level chia plotter than you’ll never ever see a cache hit ever because it’s
very large sequential writes followed by large sequential reads with a
bunch of what looks to a storage system like random writes.  You’re going
to write into the caches and never touch that cached data.  The reason chia
eats up so much ram is because it’s doing large reads and writes into ram
which completely negates any caching.  Mad max plotter profiles of a bit
different than the stock plotter but it’s the same thing.  Split it into a
bunch of large files that get loaded into ram while the plots are being
computed.
