### ISSUE TITLE
Rapiddisk module not loaded ... compile error ?

### ISSUE THREAD

**Issue by Augusto7743** [pkoutoupis/rapiddisk#56] opened 2021-05-07 08:13 UTC
Thanks very much for your rapiddisk.

I had compiled and tested in Ubuntu 20.04 and had worked correctly.
Now in Ubuntu 21.04 when trying to configure is displayed 

sudo rapiddisk -l
Please ensure that the RapidDisk module is loaded and retry.

Any wrong in compiled module ?
When compiling using only "make" is displayed

make -C src 
make[1]: Entering directory '/BTRFS/T1/RapidDisk/RapidDisk/src'
cc -c json.c -o json.o
cc -c rdsk.c -o rdsk.o
cc -c sys.c -o sys.o
cc main.c -o rapiddisk json.o rdsk.o sys.o -ljansson
cc -c json.c -DSERVER -o json-server.o
cc -c net.c -o net.o
net.c: In function ‘mgmt_thread’:
net.c:248:7: warning: passing argument 5 of ‘MHD_start_daemon’ from incompatible pointer type [-Wincompatible-pointer-types]
  248 |       &answer_to_connection, NULL, MHD_OPTION_END);
      |       ^~~~~~~~~~~~~~~~~~~~~
      |       |
      |       int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **) {aka int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, long unsigned int *, void **)}
In file included from net.c:34:
/usr/include/microhttpd.h:2443:45: note: expected ‘MHD_AccessHandlerCallback’ {aka ‘enum MHD_Result (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, long unsigned int *, void **)’} but argument is of type ‘int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, size_t *, void **)’ {aka ‘int (*)(void *, struct MHD_Connection *, const char *, const char *, const char *, const char *, long unsigned int *, void **)’}
 2443 |                   MHD_AccessHandlerCallback dh, void *dh_cls,
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
cc daemon.c -o rapiddiskd json-server.o net.o -lpthread -ljansson -lmicrohttpd
Make has completed.
make[1]: Leaving directory '/BTRFS/T1/RapidDisk/RapidDisk/src'
make -C conf 
make[1]: Entering directory '/BTRFS/T1/RapidDisk/RapidDisk/conf'
Nothing to do.
make[1]: Leaving directory '/BTRFS/T1/RapidDisk/RapidDisk/conf'
make -C doc 
make[1]: Entering directory '/BTRFS/T1/RapidDisk/RapidDisk/doc'
Nothing to do.
make[1]: Leaving directory '/BTRFS/T1/RapidDisk/RapidDisk/doc'
make -C module 
make[1]: Entering directory '/BTRFS/T1/RapidDisk/RapidDisk/module'
make -C /lib/modules/5.11.0-16-generic/build M=/BTRFS/T1/RapidDisk/RapidDisk/module
make[2]: Entering directory '/usr/src/linux-headers-5.11.0-16-generic'
  CC [M]  /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk.o
  CC [M]  /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk-cache.o
  MODPOST /BTRFS/T1/RapidDisk/RapidDisk/module/Module.symvers
  CC [M]  /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk-cache.mod.o
  LD [M]  /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk-cache.ko
  BTF [M] /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk-cache.ko
Skipping BTF generation for /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk-cache.ko due to unavailability of vmlinux
  CC [M]  /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk.mod.o
  LD [M]  /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk.ko
  BTF [M] /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk.ko
Skipping BTF generation for /BTRFS/T1/RapidDisk/RapidDisk/module/rapiddisk.ko due to unavailability of vmlinux
make[2]: Leaving directory '/usr/src/linux-headers-5.11.0-16-generic'
make[1]: Leaving directory '/BTRFS/T1/RapidDisk/RapidDisk/module'
make -C test 
make[1]: Entering directory '/BTRFS/T1/RapidDisk/RapidDisk/test'
cc rxflush.c -o rxflush
cc rxio.c -o rxio
cc rxioctl.c -o rxioctl
Make has completed.
make[1]: Leaving directory '/BTRFS/T1/RapidDisk/RapidDisk/test'
--

After I had moved rapiddisk compiled folder to /opt/ and used command "make install" and using "systemctl status rapiddiskd.service" is displayed

 rapiddiskd.service - an enclosure monitoring daemon
     Loaded: loaded (/etc/systemd/system/rapiddiskd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-04-29 05:23:43 -03; 1 weeks 0 days ago
   Main PID: 1085 (rapiddiskd)
      Tasks: 3 (limit: 4496)
     Memory: 1000.0K
     CGroup: /system.slice/rapiddiskd.service
             └─1085 /sbin/rapiddiskd

abr 29 05:23:42 A1 systemd[1]: Starting an enclosure monitoring daemon...
abr 29 05:23:43 A1 rapiddiskd[1085]: rapiddiskd: Daemon started.
abr 29 05:23:43 A1 rapiddiskd[1076]: rapiddiskd 7.1.0
abr 29 05:23:43 A1 rapiddiskd[1076]: Copyright 2011 - 2021 Petros Koutoupis
abr 29 05:23:43 A1 systemd[1]: Started an enclosure monitoring daemon.

Not is possible configure.
Any problem when compiling ? wrong install path ?

Thanks for read my topic.

**Comment by pkoutoupis** [comment] 2021-05-07 19:09
> Please ensure that the RapidDisk module is loaded and retry.
Make sure you modprobe both rapiddisk and rapiddisk_cache after installation. If you'd like to have these modules load at boot time, there are some general distribution focused instructions provided here: https://github.com/pkoutoupis/rapiddisk/wiki/Frequently-Asked-Questions-(FAQ)#how-can-i-autoload-the-kernel-modules-at-boot-time

As for the compilation warning, it is a known issue that libmicrohttpd has seen some changes in recent releases. This is being worked on in https://github.com/pkoutoupis/rapiddisk/pull/54. Please stay tuned for that update.

**Comment by Augusto7743** [comment] 2021-05-07 20:02
Thanks for your reply.
I has done exactly modproble in rapiddisk and rapiddisk-cache, but using "sudo rapiddisk –a 128" not is displayed any information about the command instead is displayed the option list how if had done rapiddisk -h
rapiddiskd.service is running.

**Comment by pkoutoupis** [comment] 2021-05-08 16:07
OK. I installed Ubuntu 21.04 and installed all the dependencies. Once I did, I did a fresh clone, make (still got the known libmicrohttpd warning) and make install. I manually loaded the modules and had no issues using the rapiddisk utility. It worked as expected with all options executed. I was able to create/remove/list and more my RAM devices. I am unable to reproduce the issue that you are seeing.

Can you please do a fresh clone and capture a step-by-step command execution (with output), so that I can hopefully see if there is anything strange going on in your system?

**Comment by Augusto7743** [comment] 2021-05-12 08:19
Creating an VirtualBox machine installed Lubuntu 21.04 64 bits and Rapiddisk compiled and installed correctly.
Rapiddisk source copied to /opt and used commands are

make
sudo make install
sudo modprobe rapiddisk
sudo modprobe rapiddisk-cache
sudo make dkms-install
sudo systemctl enable rapiddiskd.service
restarted system and
rapiddisk -a 128

rapiddisk module is working.
I had compiled the source in an user folder and after moved to /opt and done make install from /opt.
Doing an fresh install not happen problems.
The compile "error" message had created doubt for me about if was issue compiling or the system.
You had used your free time to reply me even seeing that topic being about issue with an user with few knowledge about Linux ... Thanks very much about the information to ignore compile "errors" messages.

In windows had tested and used an disk cache utility using for write back.
Unhappily even disabling or moving browsers temporary files to ramdisk browsers write extremely on disk and more worst repeated times the same files and after an time the same file is deleted. In few hours using browsers is used more 1 GB data on disk. Using an disk cache write back with long time to flush data with energy protection is solution to avoid it.
In Linux happen the same problem and thus I had searched an tool with write back for Linux and the search point to your software.
Thus I had downloaded to known better your software and not has write back feature.
I had tried configure fstab for btrfs with commit values , but not work and also the dirty_pages config not does write back for files. dirty_pages is about memory pages to be moved to swap file ?

I had installed your software and even not having write back feature look how if rapiddisk is state of art is possible feel it when seeing rapiddisk status.
Thus I has installed in my machine with an cache 64 or 128 MB.

What is the sequence writing on disk ? OS > Rapiddisk or rapiddisk > OS ?
In line command help not has details about configure option write-through or other mode.
How change write mode ?

More users need to known your software.
God bless you.
Good luck with your software.
Have an nice week.

**Comment by pkoutoupis** [comment] 2021-05-15 15:09
@Augusto7743 I am glad that you were able to get it to work in your virtual environment. Unfortunately, writeback mode does not exist and will likely never exist because of the dangers of using a writeback cache with a volatile memory technology. So, at least for the foreseeable future, the modules and userspace utilities will only support writearound and writethrough modes. Who knows, as non-volatile memory becomes more common place, that may change.

> dirty_pages is about memory pages to be moved to swap file ?

the dirty pages are of buffered I/O that has yet to flush to disk (and to the cache driver).

> What is the sequence writing on disk ? OS > Rapiddisk or rapiddisk > OS ?

Because the module supports only writethrough and writearound, the I/O pages will always pass through the modules allocated cache pages first before persisting it to the backing store (i.e. the underlying volume). However, this is all part of the same I/O operation and at no point does the I/O (when complete) exist only in memory and not on the disk.

Again, thank you for your interest in my project. I hope that you find good use for it. Anyway, seeing how this problem has been resolved for you and the compile warnings are being tracked elsewhere, I will close this ticket. If you feel like it needs to be re-opened in the future, then feel free to do so.

**Closed by pkoutoupis** 2021-05-15 15:09 UTC
